src/main/java/uk/ac/ox/cs/chaste/fc/beans/ChasteEntity.java
/**
 * 
 */
package uk.ac.ox.cs.chaste.fc.beans;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.json.simple.JSONObject;

import uk.ac.ox.cs.chaste.fc.mgmt.Tools;


/**
 * @author martin
 *
 */
public class ChasteEntity
{
	private int id;
	private String name;
	private User author;
	private String url;
	private Timestamp created;
	private HashMap<Integer, ChasteEntityVersion> versions;
	private String type;
	
	public static class SortByName implements Comparator<ChasteEntity>
	{
		@Override
		public int compare (ChasteEntity a, ChasteEntity b)
		{
			return a.compareNames(b);
		}
	}

	/**
	 * Order entities first by name, and then by id, newest (i.e. highest id) first.
	 */
	public static class SortByNameAndId implements Comparator<ChasteEntity>
	{
		@Override
		public int compare (ChasteEntity a, ChasteEntity b)
		{
			int name_compare = a.compareNames(b);
			if (name_compare == 0)
				return b.id - a.id; // a < b, i.e. prior in order, iff it has a higher id
			else
				return name_compare;
		}
	}
	
	/**
	 * Compare this entity with another by name.  Can be overridden by subclasses if raw name ordering doesn't make sense.
	 */
	protected int compareNames(ChasteEntity b)
	{
		return name.compareTo(b.name);
	}

	public ChasteEntity (int id, String name, User author, Timestamp created, String type)
	{
		this.id = id;
		this.name = name;
		this.url = Tools.convertForURL (name);
		this.created = created;
		this.author = author;
		this.type = type;
		versions = new HashMap<Integer, ChasteEntityVersion> ();
	}
	
	public void debug ()
	{
		System.out.println ("model " + name);
		for (ChasteEntityVersion v : versions.values ())
			if (v.getVersion ().equals (name))
				v.debug ();
	}
	
	public ChasteEntityVersion getVersion (String name)
	{
		for (ChasteEntityVersion v : versions.values ())
			if (v.getVersion ().equals (name))
				return v;
		return null;
	}
		
	public String getUrl ()
	{
		return url;
	}
	
	public int getId ()
	{
		return id;
	}
	
	public Map<Integer, ChasteEntityVersion> getVersions ()
	{
		return versions;
	}

	/**
	 * @return our versions in newest first ordering
	 */
	public Map<Integer, ChasteEntityVersion> getOrderedVersions()
	{
		Map<Integer, ChasteEntityVersion> sorted = new TreeMap<Integer, ChasteEntityVersion>(Collections.reverseOrder());
		sorted.putAll(versions);
		return sorted;
	}
	
	public ChasteEntityVersion getLatestVersion ()
	{
		if (versions.isEmpty())
			return null;
		List<Integer> list = new ArrayList<Integer> (versions.keySet ());
		Collections.sort (list);

		return versions.get (list.get (list.size () - 1));
	}
	
	public void addVersion (ChasteEntityVersion version)
	{
		this.versions.put (version.getId (), version);
	}
	
	public boolean hasVersions ()
	{
		return !versions.isEmpty();
	}

	public User getAuthor ()
	{
		return author;
	}
	
	public String getCreated ()
	{
		return Tools.formatTimeStamp (created);
	}

	public String getName ()
	{
		return name;
	}
	
	public String getType ()
	{
		return type;
	}
	
	public ChasteEntityVersion getVersionByFilePath (String path)
	{
		for (ChasteEntityVersion v : versions.values ())
			if (v.getFilePath ().equals (path))
				return v;
		return null;
	}

	@SuppressWarnings("unchecked")
	public JSONObject toJson ()
	{
		JSONObject json = new JSONObject ();

		json.put ("name", name);
		json.put ("created", getCreated ());
		json.put ("author", getAuthor ().getNick ());
		json.put ("id", id);

		JSONObject version = new JSONObject ();
		if (!versions.isEmpty())
			for (ChasteEntityVersion v : versions.values ())
				version.put (v.getId (), v.toJson ());

		json.put ("versions", version);
		
		return json;
	}

/*
	@SuppressWarnings("unchecked")
	public JSONObject toJsonOnlyLatestVersion ()
	{
		JSONObject json = new JSONObject ();

		json.put ("name", name);
		json.put ("created", getCreated ());
		json.put ("author", getAuthor ().getNick ());
		json.put ("id", id);

		json.put ("latestversion", getLatestVersion ().toJson ());
		
		return json;
	}*/
}

src/main/webapp/res/js/visualizers/displayPlotHC/exporting-server/java/highcharts-export/highcharts-export-web/src/main/java/com/highcharts/export/controller/ExportController.java
/**
 * @license Highcharts JS v2.3.3 (2012-11-02)
 *
 * (c) 20012-2014
 *
 * Author: Gert Vaartjes
 *
 * License: www.highcharts.com/license
 */
package com.highcharts.export.controller;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.concurrent.TimeoutException;

import javax.annotation.Resource;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.highcharts.export.converter.SVGConverter;
import com.highcharts.export.converter.SVGConverterException;
import com.highcharts.export.pool.PoolException;
import com.highcharts.export.util.MimeType;
import com.highcharts.export.util.TempDir;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import javax.servlet.http.HttpSession;
import org.apache.commons.codec.binary.Base64;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.lang.RandomStringUtils;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;

@Controller
@RequestMapping("/")
public class ExportController extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Float MAX_WIDTH = 2000.0F;
	private static final Float MAX_SCALE = 4.0F;
	protected static Logger logger = Logger.getLogger("exporter");

	@Resource(name = "svgConverter")
	private SVGConverter converter;

	/* catch all GET requests and redirect those */
	@RequestMapping(method = RequestMethod.GET)
	public String getAll(HttpSession session) {

		String tempFile = (String) session.getAttribute("tempFile");
		session.removeAttribute("tempFile");

		if (tempFile != null && !tempFile.isEmpty()) {
			// redirect to file download
			return "redirect:" + TempDir.getDownloadLink(tempFile);
		}
		// redirect to demo page
		return "redirect:demo";
	}


	@RequestMapping(value = "/demo", method = RequestMethod.GET)
	public String demo() {
		return "demo";
	}

	@RequestMapping(method = RequestMethod.POST)
	public HttpEntity<byte[]> exporter(
		@RequestParam(value = "svg", required = false) String svg,
		@RequestParam(value = "type", required = false) String type,
		@RequestParam(value = "filename", required = false) String filename,
		@RequestParam(value = "width", required = false) String width,
		@RequestParam(value = "scale", required = false) String scale,
		@RequestParam(value = "options", required = false) String options,
		@RequestParam(value = "constr", required = false) String constructor,
		@RequestParam(value = "callback", required = false) String callback,
		@RequestParam(value = "async", required = false, defaultValue = "false")  Boolean async,
		HttpServletRequest request,
		HttpSession session) throws ServletException, InterruptedException, SVGConverterException, NoSuchElementException, PoolException, TimeoutException, IOException {

		MimeType mime = getMime(type);
		String tempFilename = null;

		boolean isAndroid = request.getHeader("user-agent") != null && request.getHeader("user-agent").contains("Android");

		if (isAndroid || MimeType.PDF.equals(mime) || async) {
			tempFilename = createUniqueFileName(mime.name().toLowerCase());
		}

		String output = processRequest(svg, mime, width, scale, options, constructor, callback, tempFilename);
		ByteArrayOutputStream stream;

		if (async) {
			String link = TempDir.getDownloadLink(tempFilename);
			// write to stream
			stream = new ByteArrayOutputStream();
			stream.write(link.getBytes("utf-8"));
		} else {
			stream = ouputToStream(output, mime, tempFilename);
		}

		/* If tempFilename is not null, then we want to save the filename in session, in case of GET is used later on*/
		if (isAndroid) {
			session.setAttribute("tempFile", FilenameUtils.getName(tempFilename));
		}

		filename = getFilename(filename);

	    HttpHeaders headers = new HttpHeaders();
		headers.add("Content-Type", mime.getType() + "; charset=utf-8");
		headers.add("Content-Disposition",
                   "attachment; filename=" + filename.replace(" ", "_") + "." + mime.name().toLowerCase());
		headers.setContentLength(stream.size());

		return new HttpEntity<byte[]>(stream.toByteArray(), headers);
	}

	@RequestMapping(value = "/files/{name}.{ext}", method = RequestMethod.GET)
	public void getFile(@PathVariable("name") String name, @PathVariable("ext") String ext, HttpServletResponse response) throws SVGConverterException, IOException {
		Path path = Paths.get(TempDir.getOutputDir().toString(), name + "." + ext);

		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		try {
			stream.write(FileUtils.readFileToByteArray(new File(path.toString())));
		} catch (IOException ioex) {
			logger.error("Tried to read file from filesystem: " + ioex.getMessage());
			throw new SVGConverterException("IOException: cannot find your file to download...");
		}

		MimeType mime = MimeType.valueOf(ext.toUpperCase());

		response.reset();
		response.setCharacterEncoding("utf-8");
		response.setContentLength(stream.size());
		response.setContentType(mime.getType());
		response.setStatus(HttpStatus.OK.value());
		IOUtils.write(stream.toByteArray(), response.getOutputStream());
		response.flushBuffer();

	}

	@ExceptionHandler(IOException.class)
	public ModelAndView handleIOException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView.addObject("message", ex.getMessage());
		return modelAndView;
	}

	@ExceptionHandler(TimeoutException.class)
	public ModelAndView handleTimeoutException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView
				.addObject(
						"message",
						"Timeout converting SVG, is your file this big, or maybe you have a syntax error in the javascript callback?");
		return modelAndView;
	}

	@ExceptionHandler(PoolException.class)
	public ModelAndView handleServerPoolException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView
				.addObject(
						"message",
						"Sorry, the server is handling too many requests at the moment. Please try again.");
		return modelAndView;
	}

	@ExceptionHandler(SVGConverterException.class)
	public ModelAndView handleSVGRasterizeException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView
				.addObject(
						"message",
						"Something went wrong while converting. " + ex.getMessage());
		return modelAndView;
	}

	@ExceptionHandler(InterruptedException.class)
	public ModelAndView handleInterruptedException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView
				.addObject(
						"message",
						"It took too long time to process the options, no SVG is created. Make sure your javascript is correct");
		return modelAndView;
	}

	@ExceptionHandler(ServletException.class)
	public ModelAndView handleServletException(Exception ex) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("error");
		modelAndView.addObject("message", ex.getMessage());
		return modelAndView;
	}

	/*
	 * UTILS METHODS
	 */

	private String processRequest(String svg, MimeType mime, String width, String scale, String options, String constructor, String callback, String filename) throws SVGConverterException, PoolException, NoSuchElementException, TimeoutException, ServletException {

		Float parsedWidth = widthToFloat(width);
		Float parsedScale = scaleToFloat(scale);
		options = sanitize(options);
		String input;
		String output;

		boolean convertSvg = false;

		if (options != null) {
			// create a svg file out of the options
			input = options;
			callback = sanitize(callback);
		} else {
			// assume SVG conversion
			if (svg == null) {
				throw new ServletException(
						"The manadatory svg POST parameter is undefined.");
			} else {
				svg = sanitize(svg);
				if (svg == null) {
					throw new ServletException(
							"The manadatory svg POST parameter is undefined.");
				}
				convertSvg = true;
				input = svg;
			}
		}

		if (convertSvg && mime.equals(MimeType.SVG)) {
				output = converter.redirectSVG(input, filename);
		} else {
			output = converter.convert(input, mime, constructor, callback, parsedWidth, parsedScale, filename);
		}

		return output;
	}

	private String getFilename(String name) {
		name = sanitize(name);
		return (name != null) ? name : "chart";
	}

	private static MimeType getMime(String mime) {
		MimeType type = MimeType.get(mime);
		if (type != null) {
			return type;
		}
		return MimeType.PNG;
	}

	private static String sanitize(String parameter) {
		if (parameter != null && !parameter.trim().isEmpty() && !(parameter.compareToIgnoreCase("undefined") == 0)) {
			return parameter.trim();
		}
		return null;
	}

	private static Float widthToFloat(String width) {
		width = sanitize(width);
		if (width != null) {
			Float parsedWidth = Float.valueOf(width);
			if (parsedWidth.compareTo(MAX_WIDTH) > 0) {
				return MAX_WIDTH;
			}
			if (parsedWidth.compareTo(0.0F) > 0) {
				return parsedWidth;
			}
		}
		return null;
	}

	private static Float scaleToFloat(String scale) {
		scale = sanitize(scale);
		if (scale != null) {

src/main/webapp/WEB-INF/Compare.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<t:skeleton headerImports="${PageHeader}" notes="${Notifications}" user="${User}" title="${Title}Comparison - " contextPath="${contextPath}">
    <h1 id="heading">Comparison</h1>
    
    <div id="entitiesToCompare">
    loading...
    </div>
    
	<div id="filedetails">
		<div class="closebtn"><small>
		    <a id="exportPlot" style="display: none;">export plot data</a> | 
		    <a id="fileclose">&otimes; close</a>
		</small></div>
    	<h3 id="filename"></h3>
	    <div id="filedisplay"></div>
	</div>
    
    
    <div id="files">
	    <h3 id="outputFileHeadline"></h3>
	    <table id="filestable">
		</table>
	</div>
</t:skeleton>

src/main/webapp/WEB-INF/Contact.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>

<t:skeleton headerImports="${PageHeader}" notes="${Notifications}" user="${User}" title="${Title}Contact - " contextPath="${contextPath}">
    <h1>Contact</h1>
    <p>
        Please direct queries about this website to <a href="mailto:jonathan.cooper@cs.ox.ac.uk?subject=Cardiac%20Web%20Lab&cc=gary.mirams@cs.ox.ac.uk">Jonathan Cooper</a>.
    </p>
    <p>
        The Functional Curation concept was invented by <a href="http://www.cs.ox.ac.uk/people/gary.mirams/">Gary Mirams</a> and <a href="http://www.cs.ox.ac.uk/people/jonathan.cooper/">Jonathan Cooper</a>.
        This web interface was created by <a href="http://www.sbi.uni-rostock.de/team/single/martin-scharm/">Martin Scharm</a>.
    </p>

    <p>
       <img alt="Team - Gary Mirams" style="float:left;margin:5px 10px 5px 0;" src="/FunctionalCuration/res/img/team/gary.jpg" width="150">
       <a href="http://www.cs.ox.ac.uk/people/gary.mirams/">Gary Mirams</a> is a mathematical modeller who started working on
       cardiac electrophysiology in 2009; and has been trying to work out how best to select, re-use and refine/develop cardiac models
       since then. He has written a few <a href="http://mirams.wordpress.com/">blog entries</a> about the motivation for this website.
    </p>
    <p style="clear:left;">
        <img alt="Team - Jonathan Cooper" style="float:left;margin:5px 10px 5px 0;" src="/FunctionalCuration/res/img/team/jonathan.jpg" width="150"/>
        <a href="http://www.cs.ox.ac.uk/people/jonathan.cooper/">Jonathan Cooper</a> is interested in using software engineering and computer science techniques 
        to improve the lives of research scientists. Most of his work has revolved around the development and use of 
        "domain specific languages" for describing and working with models of biological systems.
    </p>
    <p style="clear:left;">
        <img alt="Team - Martin Scharm" style="float:left;margin:5px 10px 10px 0;" src="/FunctionalCuration/res/img/team/martin.jpg" width="150"/>
        <a href="http://www.sbi.uni-rostock.de/team/single/martin-scharm/">Martin Scharm</a> created this web interface. 
        He is developing tools to identify differences between computational models and to 
        display these differences in a human readable format, to support model reuse.
    </p>

</t:skeleton>

src/main/webapp/WEB-INF/Entity.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<t:skeleton headerImports="${PageHeader}" notes="${Notifications}" user="${User}" title="${Title}${entity.type} - " contextPath="${contextPath}">
    <c:choose>
        <c:when test="${entity.type eq 'model'}"><c:set var="otherType" value="protocol"/></c:when>
        <c:otherwise><c:set var="otherType" value="model"/></c:otherwise>
    </c:choose>
    <h1 id="entityname">
        <small>${fn:toUpperCase(fn:substring(entity.type, 0, 1))}${fn:toLowerCase(fn:substring(entity.type, 1,fn:length(entity.type)))}: </small>
        <span>${entity.name}</span>
    </h1>
    
	<div class="suppl">
	    <small>Created <time>${entity.created}</time> by <em>${entity.author}</em>. 
    	    <c:if test="${entity.author == User.nick || User.admin}">
    	    	Delete ${entity.type}: <a id='deleteEntity' title="delete all versions of this ${entity.type}"><img src="${contextPath}/res/img/delete.png" alt="delete all versions of this ${entity.type}" title="delete all versions of this ${entity.type}"/></a>
    	    </c:if>
    	    
    		<c:if test="${User.allowedToForceNewExperiment && entity.type == 'experiment'}">
    			<a id="rerunExperiment"><img src="${contextPath}/res/img/refresh.png" alt="rerun experiment" title="rerun experiment"/></a> <span id="rerunExperimentAction"></span>
    		</c:if>
    		<c:if test="${entity.type == 'experiment'}">
    			<br/>Corresponding model: 
    			<a href="${contextPath}/${correspondingModel.entity.type}/${correspondingModel.entity.url}/${correspondingModel.entity.id}/${correspondingModel.url}/${correspondingModel.id}">${correspondingModel.name}</a>
    			&amp; protocol: 
    			<a href="${contextPath}/${correspondingProtocol.entity.type}/${correspondingProtocol.entity.url}/${correspondingProtocol.entity.id}/${correspondingProtocol.url}/${correspondingProtocol.id}">${correspondingProtocol.name}</a>
    		</c:if>
		</small>
	</div>
	
    
    <div id="entitydetails">
    	<h2>Versions</h2>
    	<div id="entityversionlist">
    		<c:if test="${entity.type == 'experiment'}">
    			<p id='expversioncolorlegend'>
    				Status Legend:
    				<span class="experiment-QUEUED">queued</span>
    				<span class="experiment-RUNNING">running</span>
    				<span class="experiment-INAPPLICABLE">inapplicable</span>
    				<span class="experiment-FAILED">failed</span>
    				<span class="experiment-PARTIAL">partial failure</span>
    				<span class="experiment-SUCCESS">success</span>
    			</p>
    		</c:if>
    		<c:if test="${User.allowedToCreateEntityVersion and entity.type ne 'experiment'}">
				<small>(<a href="${contextPath}/${entity.type}/createnew/?newentityname=${entity.id}">add new version</a>)</small>
			</c:if>
			<div id="entityversionlist_content">
				<c:forEach items="${entity.orderedVersions}" var="version" >
		    		<p id="version-item-${version.value.id}"
		    		   title="${version.value.created} -- Visibility: ${version.value.visibility}<c:if test="${entity.type == 'experiment'}"> -- ${version.value.status}</c:if>"
		    		   class="entityviz-${version.value.visibility}<c:if test="${entity.type == 'experiment'}"> experiment-${version.value.status}</c:if>">
	    				<input type="checkbox" value="${version.value.id}" class="comparisonCheckBox"/>
						<strong><c:choose>
						  <c:when test="${entity.type == 'experiment' and version.value.status == 'INAPPLICABLE'}">${version.value.version}</c:when>
						  <c:otherwise><a class="entityversionlink" href="${contextPath}/${entity.type}/${entity.url}/${entity.id}/${version.value.url}/${version.value.id}/">${version.value.version}</a></c:otherwise>
						</c:choose></strong>
						by <em>${version.value.author}
						<c:if test="${entity.author == User.nick || User.admin}">
					    	<a id='deleteVersion-${version.value.id}' class="deleteVersionLink"><img src="${contextPath}/res/img/delete.png" alt="delete version" title="delete this version of the ${entity.type}" /></a>
					    </c:if></em><c:if test="${not empty version.value.commitMessage}"> &mdash; <small>${version.value.commitMessage}</small></c:if><br/>
					    <c:if test="${entity.type == 'experiment' and (version.value.status == 'FAILED' or version.value.status == 'INAPPLICABLE') and version.value.returnText != 'finished'}">
					        <span class="suppl"><small>${version.value.returnText}</small></span><br/>
					    </c:if>
    					<span class="suppl"><small>created </small> <time>${version.value.created}</time> <small>containing</small> ${version.value.numFiles} file<c:if test="${version.value.numFiles!=1}">s</c:if>.</span>
				    </p>
		        </c:forEach>
			</div>
			<div id="compareVersionsSelectors">
			    [<small><a id="compareVersionsSelectorsAll">select all</a></small>]
			    [<small><a id="compareVersionsSelectorsNone">select none</a></small>]
			</div>
			<button id="compareVersions">compare selected versions</button>
		</div>
    </div>
    
    <div id="entityversion">
    	<div class="closebtn"><small><a id="entityversionclose">&otimes; close / see version table</a></small></div>
    	<h2 id="entityversionname"></h2>
	    <div class="suppl"><small>
	    <c:choose>
    	    <c:when test="${entity.type == 'experiment'}">Run</c:when>
    	    <c:otherwise>Created</c:otherwise>
	    </c:choose>
	    <time id="entityversiontime"></time> by <em id="entityversionauthor"></em>.
		    <c:if test="${User.isAllowedToUpdateEntity(entity) && entity.type != 'experiment'}">
		    	Change visibility: 
		    	<select id="versionVisibility">
		    	    <c:if test="${User.admin}">
		    	        <option VALUE="MODERATED" id="visibility-MODERATED">MODERATED</option>
	    	        </c:if>
			    	<option value="PUBLIC" id="visibility-PUBLIC">PUBLIC</option>
			    	<option value="RESTRICTED" id="visibility-RESTRICTED">RESTRICTED</option>
			    	<option value="PRIVATE" id="visibility-PRIVATE">PRIVATE</option>
		    	</select>
                <img src="${contextPath}/res/img/info.png" alt="help" title="Public = anyone can view &#10;Restricted = logged-in users can view &#10;Private = only you can view"/>
		    	<span id="versionVisibilityAction"></span>
		    </c:if>
		    <span id="exptStatus"></span>
		    <c:if test="${entity.author == User.nick || User.admin}">
		    	Delete version: <a id='deleteVersion'><img src="${contextPath}/res/img/delete.png" alt="delete version" title="delete this version of the ${entity.type}" /></a>
		    </c:if>
		    <c:if test="${entity.type != 'experiment' && User.isAllowedToCreateNewExperiment()}">
		        Run experiments: <a class='runExpts' title="run experiments using this ${entity.type}"><img alt="run experiments using this ${entity.type}" src="${contextPath}/res/img/batch.png"/></a>
		    </c:if>
		    <c:if test="${entity.type == 'protocol' && User.admin}">
		        Refresh interface: <a id='updateInterface'><img src="${contextPath}/res/img/refresh.png" alt="refresh interface" title="recompute this protocol's ontology term interface"/></a>
		    </c:if>
		    </small>
	    </div>
	    
	    <div id="running-experiment-note" style="display: none;">
	       <p>
	           This experiment has not yet finished running, and so no result files are available.
	           You can refresh the page to see if it has completed.
	       </p>
	    </div>
	    
	    <div id="experiment-files-switcher">
	    	<button style="float:left;" id="experiment-files-switcher-files" title="View files associated with this ${entity.type}">Files</button>
            <button style="margin-left:5px; float:left;" id="experiment-files-switcher-exp" title="View &amp; compare experiments using this ${entity.type}">Compare ${otherType}s</button>
	    	<c:if test="${entity.type == 'protocol'}">
	    	    <button style="margin-left:5px; float:left;" id="compare-all-models" title="Compare all available models under this protocol">Compare all</button>
	    	</c:if>
		<br/>
	    </div>
	    
	    <div id="entityversiondetails">
			<div id="entityversionfiledetails">
	    		<div class="closebtn"><small>
	    		    <a id="exportPlot" style="display: none;">export plot data |</a>
			    <a id="zoomFile">zoom |</a>
	    		    <a id="entityversionfileclose">&otimes; close</a>
	    		</small></div>
		    	<h3 id="entityversionfilename"></h3>
			    <div class="suppl"><small>Created <time id="entityversionfiletime"></time> by <em id="entityversionfileauthor"></em>.</small></div>
			    <div id="entityversionfiledisplay"></div>
			</div>
			
		    <div id="entityversionfiles">
			    <h3>Files attached to this version</h3>
			    <p id="parse_status"></p>
			    <table id="entityversionfilestable">
				</table>
				<a id='downloadArchive' title="Download a 'combine' format archive of all the files">
				     <img src="${contextPath}/res/img/document-save-5.png" alt="Download" title="Download a 'combine' format archive of all the files"/> 
				     Download archive of all files
				</a>
    	        <div id="entityversionfilesreadme"></div>
			</div>
		</div>
		
		<div id="entityexperimentlist">
		    <h3>Experiments using this ${entity.type}</h3>
		    <p>
		        This ${entity.type} has been run with the following ${otherType}s.
		        Click to view the latest results of each single experiment, or select multiple experiments to compare them.
                <c:if test="${entity.type != 'experiment' && User.isAllowedToCreateNewExperiment()}">
                    You may also <a class='runExpts' title="Run experiments using this ${entity.type}">run new experiments using this ${entity.type}</a> and your own ${otherType}s.
                </c:if>
		    </p>
			<div id="entityexperimentlistpartners"><ul></ul></div>
			<div id="entityexperimentlistpartnersact">
				[<a id="entityexperimentlistpartnersactall">select all</a>]
				<span id="entityexperimentlist_span_latest">[<a id="entityexperimentlistpartnersactlatest">select latest</a>]</span>
				[<a id="entityexperimentlistpartnersactnone">select none</a>]
				<br/>
				<button id="entityexperimentlist_showallversions">show all versions</button>
				<button id="entityexperimentlistpartnersactcompare">compare selected experiments</button>
			</div>
		</div>
		
	</div>
</t:skeleton>